spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mochat?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&autoReconnect=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    filters: stat,wall
  devtools:
    restart:
      #热部署生效
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    database: 1

#OSS
oss:
  endpoint: xxxx
  accessKeyId: xxxx
  accessKeySecret: xxxx
  bucketName: xxxx
